language: node_js
os: linux
dist: xenial
node_js: [14]

cache:
  yarn: true

install:
  - yarn

script:
  - yarn ci

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      npm config set registry https://npm.pkg.github.com \
      && git config --unset lfs.https://github.com/applandinc/scanner.git/info/lfs.access \
      && git remote set-url origin https://${GH_TOKEN}@github.com/applandinc/scanner.git \
      && yarn run semantic-release
    on:
      branch: main
