language: node_js
os: linux
dist: xenial
node_js: [14]

cache:
  yarn: true

install:
  - yarn

script:
  - yarn ci

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      npm config set registry https://npm.pkg.github.com \
      && git config lfs.url http://${GH_TOKEN}@github.com/applandinc/scanner.git \
      && GIT_TRACE=1 GIT_CURL_VERBOSE=1 yarn run semantic-release
    on:
      branch: main
