language: node_js
os: linux
dist: xenial
node_js: [14]

cache:
  yarn: true

install:
  - yarn

script:
  - yarn ci

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo "https://${GH_TOKEN}:@github.com" > .git/credentials \
      && git config credential.helper "store --file=.git/credentials" \
      && npm config set registry https://npm.pkg.github.com \
      && yarn run semantic-release
    on:
      branch: main
