language: node_js
os: linux
dist: xenial
node_js: ['14.18.1']

before_install:
  - sudo apt-get update && sudo apt-get -y install jq

install:
  - yarn

script:
  - yarn ci

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo -e "machine github.com\n  login ${GH_TOKEN}" > ~/.netrc \
        && yarn semantic-release
    on:
      branch: main
