scanners:
  - id: circularDependency
  - id: http500
  - id: missingContentType
  - id: nPlusOneQuery
  - id: slowHttpServerRequest
  - id: slowQuery
  - id: tooManyJoins
  - id: tooManyUpdates
  - id: updateInGetRequest
  # Required labels: secret, log
  # - id: secretInLog
  # Required labels: security.authentication, security.authorization
  # - id: authzBeforeAuthn
  # Required labels: security.authentication
  # Optional labels: public
  # - id: missingAuthentication
  # Required labels: dao.materialize
  # - id: unbatchedMaterializedQuery
