checks:
  - rule: circularDependency
  - rule: http500
  - rule: missingContentType
  - rule: nPlusOneQuery
#  - rule: slowHttpServerRequest
#  - rule: slowQuery
#  - rule: tooManyJoins
#  - rule: tooManyUpdates
#  - rule: updateInGetRequest
# Required labels: secret, log
# - rule: secretInLog
# Required labels: security.authentication, security.authorization
# - rule: authzBeforeAuthn
# Required labels: security.authentication
# Optional labels: public
# - rule: missingAuthentication
# Required labels: dao.materialize
# - rule: unbatchedMaterializedQuery
